steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/${PROJECT_ID}/test', '.']
      id: docker build
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/${PROJECT_ID}/test']
      id: docker push
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['container','clusters', 'get-credentials', 'gke-test-cluster', '--zone', 'asia-northeast1-c', '--project', '${PROJECT_ID}']
      id: cloud container clusters get-credentials
    - name: "gcr.io/cloud-builders/kubectl"
      args: ['apply','-f', 'k8s-gke-test.yaml']
      env:
        - "CLOUDSDK_COMPUTE_REGION=asia-northeast1-c"
        - "CLOUDSDK_CONTAINER_CLUSTER=gke-test-cluster"
      id: kubectl apply
     